POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Koodarin päiväkirja",
    "author": "Valvoja",
    "url": "koodarinpaivakirja.com",
    "likes": 20,
    "userId": "5e4532750633ba3dbe8a2e31"
}